name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$ENV_FILE" > .env
          cat .env

      - name: Build Application
        run: bun run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: /home/carabaopro-product-check-fe/htdocs/product-check.carabaopro.com
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.github' \
            --exclude='src' \
            --exclude='*.ts' \
            --exclude='*.tsx' \
            --exclude='*.js' \
            --exclude='*.jsx' \
            --exclude='*.json' \
            --exclude='*.config.*' \
            --exclude='.env' \
            --exclude='.env.*' \
            --exclude='README.md' \
            --exclude='.gitignore' \
            --exclude='.cursorrules' \
            --exclude='eslint.config.js' \
            --exclude='tsconfig.*' \
            --exclude='vite.config.ts' \
            --exclude='components.json' \
            --exclude='bun.lock' \
            ./dist/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

      - name: Setup PM2 Configuration and Start Application
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
            cd /home/carabaopro-product-check-fe/htdocs/product-check.carabaopro.com && \
            echo 'Creating ecosystem.config.cjs for PM2...' && \
            cat > ecosystem.config.cjs << 'EOF'
            module.exports = {
              apps: [{
                name: 'carabao-product-management-app',
                script: 'node_modules/.bin/vite',
                args: 'preview --host 0.0.0.0 --port 3011',
                instances: 1,
                autorestart: true,
                watch: false,
                max_memory_restart: '1G',
                env: {
                  NODE_ENV: 'production'
                },
                cwd: '/home/carabaopro-product-check-fe/htdocs/product-check.carabaopro.com'
              }]
            };
            EOF
            && \
            echo 'Installing dependencies on VPS...' && \
            bun install --production && \
            echo 'Stopping existing PM2 process...' && \
            pm2 delete carabao-product-management-app || true && \
            echo 'Starting application with PM2...' && \
            pm2 start ecosystem.config.cjs && \
            echo 'Saving PM2 configuration...' && \
            pm2 save && \
            echo 'PM2 status:' && \
            pm2 status
          "
