name: Deploy To Lexa VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build frontend
        run: bun run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create .env.production
        env:
          FRONTEND_ENV: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$FRONTEND_ENV" > .env.production

      - name: Upload to VPS
        env:
          DEPLOY_PATH: /home/product-check-carabaopro/htdocs/product-check.carabaopro.com
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.github' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

      - name: Restart PM2 process
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
            cd /home/product-check-carabaopro/htdocs/product-check.carabaopro.com && \
            source ~/.bashrc && \
            bun install && \
            /usr/local/lib/node_modules/pm2/bin/pm2 delete carabao-product-check-fe || true && \
            /usr/local/lib/node_modules/pm2/bin/pm2 start ecosystem.config.cjs --env production && \
            /usr/local/lib/node_modules/pm2/bin/pm2 save
          "
